### ISSUE TITLE
Logging instead of printing

### ISSUE THREAD

**Issue by cogitor** [Otann/wrench#8]
First of all, thank you for the lovely configuration library! :)

The current implementation is printing to stdout https://github.com/Otann/wrench/blob/2c8c1c98aab8a212131c612036250b968dd716eb/src/wrench/core.clj#L93, which is pretty useful. 

It would be even better if the side-effect is actually a standard debug logging operation, which could be ignored if one wants to :). Same for the missing configuration.

**Comment by Otann** [comment]
Thank you for your feedback!

Added `validate-and-log`, which relies on `clojure/tools.logging`.
Released `0.3.3` to [Clojars](https://clojars.org/wrench).
